DELETE FROM games WHERE Platform = "Apple IIGS";
DELETE FROM games WHERE Platform = "Amstrad GX4000";
DELETE FROM games WHERE Platform = "Android";
DELETE FROM games WHERE Platform = "Atari 5200";
DELETE FROM games WHERE Platform = "Atari 7800";
DELETE FROM games WHERE Platform = "Atari 800";
DELETE FROM games WHERE Platform = "Atari Jaguar";
DELETE FROM games WHERE Platform = "Atari Jaguar CD";
DELETE FROM games WHERE Platform = "Apple iOS";
DELETE FROM games WHERE Platform = "Apple Mac OS";
DELETE FROM games WHERE Platform = "Bally Astrocade";
DELETE FROM games WHERE Platform = "BBC Microcomputer System";
DELETE FROM games WHERE Platform = "Camputers Lynx";
DELETE FROM games WHERE Platform = "Casio Loopy";
DELETE FROM games WHERE Platform = "Casio PV-1000";
DELETE FROM games WHERE Platform = "Atari XEGS";
DELETE FROM games WHERE Platform = "Nintendo Famicom Disk System";
DELETE FROM games WHERE Platform = "Nintendo Pokemon Mini";
DELETE FROM games WHERE Platform = "Nintendo Switch";
DELETE FROM games WHERE Platform = "Nintendo Wii U";
DELETE FROM games WHERE Platform = "Sega CD 32X";
DELETE FROM games WHERE Platform = "Sony Playstation 3";
DELETE FROM games WHERE Platform = "Coleco ADAM";
DELETE FROM games WHERE Platform = "Commodore 128";
DELETE FROM games WHERE Platform = "Commodore 64";
DELETE FROM games WHERE Platform = "Commodore CDTV";
DELETE FROM games WHERE Platform = "Commodore MAX Machine";
DELETE FROM games WHERE Platform = "Commodore PET";
DELETE FROM games WHERE Platform = "Commodore Plus 4";
DELETE FROM games WHERE Platform = "Commodore VIC-20";
DELETE FROM games WHERE Platform = "Dragon 32/64";
DELETE FROM games WHERE Platform = "EACA EG2000 Colour Genie";
DELETE FROM games WHERE Platform = "Elektronika BK";
DELETE FROM games WHERE Platform = "Emerson Arcadia 2001";
DELETE FROM games WHERE Platform = "Enterprise";
DELETE FROM games WHERE Platform = "Entex Adventure Vision";
DELETE FROM games WHERE Platform = "Epoch Game Pocket Computer";
DELETE FROM games WHERE Platform = "Epoch Super Cassette Vision";
DELETE FROM games WHERE Platform = "Exelvision EXL 100";
DELETE FROM games WHERE Platform = "Exidy Sorcerer";
DELETE FROM games WHERE Platform = "Fairchild Channel F";
DELETE FROM games WHERE Platform = "Fujitsu FM Towns Marty";
DELETE FROM games WHERE Platform = "Fujitsu FM-7";
DELETE FROM games WHERE Platform = "Funtech Super Acan";
DELETE FROM games WHERE Platform = "Game Wave Family Entertainment System";
DELETE FROM games WHERE Platform = "GamePark GP32";
DELETE FROM games WHERE Platform = "GameWave";
DELETE FROM games WHERE Platform = "Hartung Game Master";
DELETE FROM games WHERE Platform = "Hector HRX";
DELETE FROM games WHERE Platform = "Interton VC 4000";
DELETE FROM games WHERE Platform = "Jupiter Ace";
DELETE FROM games WHERE Platform = "Linux";
DELETE FROM games WHERE Platform = "Magnavox Odyssey";
DELETE FROM games WHERE Platform = "Magnavox Odyssey 2";
DELETE FROM games WHERE Platform = "Matra and Hachette Alice";
DELETE FROM games WHERE Platform = "Mattel Aquarius";
DELETE FROM games WHERE Platform = "Mattel HyperScan";
DELETE FROM games WHERE Platform = "Mega Duck";
DELETE FROM games WHERE Platform = "Memotech MTX512";
DELETE FROM games WHERE Platform = "Microsoft Xbox";
DELETE FROM games WHERE Platform = "Microsoft Xbox 360";
DELETE FROM games WHERE Platform = "Microsoft Xbox One";
DELETE FROM games WHERE Platform = "MS-DOS";
DELETE FROM games WHERE Platform = "Not Rated";
DELETE FROM games WHERE Platform = "Adventure";
DELETE FROM games WHERE Platform = "MUGEN";
DELETE FROM games WHERE Platform = "Namco System 22";
DELETE FROM games WHERE Platform = "NEC PC-8801";
DELETE FROM games WHERE Platform = "NEC PC-9801";
DELETE FROM games WHERE Platform = "NEC PC-FX";
DELETE FROM games WHERE Platform = "Nintendo Satellaview";
DELETE FROM games WHERE Platform = "Nokia N-Gage";
DELETE FROM games WHERE Platform = "Nuon";
DELETE FROM games WHERE Platform = "OpenBOR";
DELETE FROM games WHERE Platform = "Oric Atmos";
DELETE FROM games WHERE Platform = "Ouya";
DELETE FROM games WHERE Platform = "Philips CD-i";
DELETE FROM games WHERE Platform = "Philips VG 5000";
DELETE FROM games WHERE Platform = "Philips Videopac+";
DELETE FROM games WHERE Platform = "Pinball";
DELETE FROM games WHERE Platform = "RCA Studio II";
DELETE FROM games WHERE Platform = "SAM Coupé";
DELETE FROM games WHERE Platform = "Sega Dreamcast VMU";
DELETE FROM games WHERE Platform = "Sega Hikaru";
DELETE FROM games WHERE Platform = "Sega Model 1";
DELETE FROM games WHERE Platform = "Sega Model 2";
DELETE FROM games WHERE Platform = "Sega Model 3";
DELETE FROM games WHERE Platform = "Sega Pico";
DELETE FROM games WHERE Platform = "Sega SC-3000";
DELETE FROM games WHERE Platform = "Sega SG-1000";
DELETE FROM games WHERE Platform = "Sega ST-V";
DELETE FROM games WHERE Platform = "Sega System 16";
DELETE FROM games WHERE Platform = "Sega System 32";
DELETE FROM games WHERE Platform = "Sega Triforce";
DELETE FROM games WHERE Platform = "Sharp MZ-2500";
DELETE FROM games WHERE Platform = "Sharp X1";
DELETE FROM games WHERE Platform = "Sharp X68000";
DELETE FROM games WHERE Platform = "Sinclair ZX-81";
DELETE FROM games WHERE Platform = "Sony Playstation 4";
DELETE FROM games WHERE Platform = "Sony Playstation 5";
DELETE FROM games WHERE Platform = "Sony Playstation Vita";
DELETE FROM games WHERE Platform = "Sony PocketStation";
DELETE FROM games WHERE Platform = "Sony PSP Minis";
DELETE FROM games WHERE Platform = "Sord M5";
DELETE FROM games WHERE Platform = "Spectravideo";
DELETE FROM games WHERE Platform = "Taito Type X";
DELETE FROM games WHERE Platform = "Tandy TRS-80";
DELETE FROM games WHERE Platform = "Tapwave Zodiac";
DELETE FROM games WHERE Platform = "Texas Instruments TI 99/4A";
DELETE FROM games WHERE Platform = "Tiger Game.com";
DELETE FROM games WHERE Platform = "Tomy Tutor";
DELETE FROM games WHERE Platform = "TRS-80 Color Computer";
DELETE FROM games WHERE Platform = "Vector-06C";
DELETE FROM games WHERE Platform = "VTech CreatiVision";
DELETE FROM games WHERE Platform = "VTech Socrates";
DELETE FROM games WHERE Platform = "Watara Supervision";
DELETE FROM games WHERE Platform = "Web Browser";
DELETE FROM games WHERE Platform = "Windows";
DELETE FROM games WHERE Platform = "Action";
DELETE FROM games WHERE Platform = "Windows 3.X";
DELETE FROM games WHERE Platform = "WoW Action Max";
DELETE FROM games WHERE Platform = "XaviXPORT";
DELETE FROM games WHERE Platform = "ZiNc";
DELETE FROM images_temp WHERE type = "Banner";
DELETE FROM images_temp WHERE type = "Box - 3D";
DELETE FROM images_temp WHERE type = "Box - Back";
DELETE FROM images_temp WHERE type = "Disc";
DELETE FROM images_temp WHERE type = "Fanart - Background";
DELETE FROM images_temp WHERE type = "Fanart - Box - Front";
DELETE FROM images_temp WHERE type = "Cart - 3D";
DELETE FROM images_temp WHERE type = "Screenshot - Game Over";
DELETE FROM images_temp WHERE type = "Screenshot - Game Select";
DELETE FROM images_temp WHERE type = "Screenshot - Game Title";
DELETE FROM images_temp WHERE type = "Screenshot - High Scores";
DELETE FROM images_temp WHERE type = "Advertisement Flyer - Back";
DELETE FROM images_temp WHERE type = "Advertisement Flyer - Front";
DELETE FROM images_temp WHERE type = "Arcade - Cabinet";
DELETE FROM images_temp WHERE type = "Arcade - Circuit Board";
DELETE FROM images_temp WHERE type = "Arcade - Control Panel";
DELETE FROM images_temp WHERE type = "Arcade - Controls Information";
DELETE FROM images_temp WHERE type = "Arcade - Marquee";
DELETE FROM images_temp WHERE type = "Box - Front - Reconstructed";
DELETE FROM images_temp WHERE type = "Fanart - Disc";
DELETE FROM images_temp WHERE type = "Box - Back - Reconstructed";
DELETE FROM images_temp WHERE type = "Fanart - Cart - Front";
DELETE FROM images_temp WHERE type = "Fanart - Box - Back";
DELETE FROM images_temp WHERE type = "Cart - Back";
DELETE FROM images_temp WHERE type = "Fanart - Cart - Back";
DELETE FROM images_temp WHERE region = "Asia";
DELETE FROM images_temp WHERE region = "Australia";
DELETE FROM images_temp WHERE region = "Brazil";
DELETE FROM images_temp WHERE region = "Canada";
DELETE FROM images_temp WHERE region = "China";
DELETE FROM images_temp WHERE region = "Finland";
DELETE FROM images_temp WHERE region = "France";
DELETE FROM images_temp WHERE region = "Germany";
DELETE FROM images_temp WHERE region = "Greece";
DELETE FROM images_temp WHERE region = "Hong Kong";
DELETE FROM images_temp WHERE region = "Italy";
DELETE FROM images_temp WHERE region = "Japan";
DELETE FROM images_temp WHERE region = "Korea";
DELETE FROM images_temp WHERE region = "Norway";
DELETE FROM images_temp WHERE region = "Oceania";
DELETE FROM images_temp WHERE region = "Russia";
DELETE FROM images_temp WHERE region = "South America";
DELETE FROM images_temp WHERE region = "Spain";
DELETE FROM images_temp WHERE region = "Sweden";
DELETE FROM images_temp WHERE region = "The Netherlands";
DELETE FROM images_temp WHERE region = "United Kingdom";
INSERT INTO images_temp2(`DatabaseID`, `filename`, `type`,`region`)
SELECT images_temp.DatabaseID, images_temp.filename, images_temp.type, images_temp.region from images_temp 
INNER JOIN games
ON games.DatabaseID = images_temp.DatabaseID;
UPDATE images_temp2 SET region="None" WHERE region = '';
INSERT INTO images_temp3(`DatabaseID`, `filename`, `type`,`region`)
SELECT images_temp2.DatabaseID, images_temp2.filename, images_temp2.type, images_temp2.region from images_temp2 
WHERE images_temp2.type = "BOX - Front" group by images_temp2.DatabaseID;
INSERT INTO images_temp3(`DatabaseID`, `filename`, `type`,`region`)
SELECT images_temp2.DatabaseID, images_temp2.filename, images_temp2.type, images_temp2.region from images_temp2 
WHERE images_temp2.type = "Clear Logo" group by images_temp2.DatabaseID;
INSERT INTO images_temp3(`DatabaseID`, `filename`, `type`,`region`)
SELECT images_temp2.DatabaseID, images_temp2.filename, images_temp2.type, images_temp2.region from images_temp2 
WHERE images_temp2.type = "Screenshot - Gameplay" group by images_temp2.DatabaseID;
UPDATE images_temp3 set type ="box2dfront" WHERE type="BOX - Front";
UPDATE images_temp3 set type ="wheel" WHERE type="Clear Logo";
UPDATE images_temp3 set type ="screenshot" WHERE type="Screenshot - Gameplay";
UPDATE games SET Platform ="3do" WHERE Platform = "3DO Interactive Multiplayer";
UPDATE games SET Platform ="amstradcpc" WHERE Platform = "Amstrad CPC";
UPDATE games SET Platform ="mame" WHERE Platform = "Arcade";
UPDATE games SET Platform ="atari2600" WHERE Platform = "Atari 2600";
UPDATE games SET Platform ="lynx" WHERE Platform = "Atari Lynx";
UPDATE games SET Platform ="atarist" WHERE Platform = "Atari ST";
UPDATE games SET Platform ="colecovision" WHERE Platform = "ColecoVision";
UPDATE games SET Platform ="amiga" WHERE Platform = "Commodore Amiga";
UPDATE games SET Platform ="amiga" WHERE Platform = "Commodore Amiga CD32";
UPDATE games SET Platform ="vectrex" WHERE Platform = "GCE Vectrex";
UPDATE games SET Platform ="intellivision" WHERE Platform = "Mattel Intellivision";
UPDATE games SET Platform ="MSX" WHERE Platform = "Microsoft MSX";
UPDATE games SET Platform ="MSX" WHERE Platform = "Microsoft MSX2";
UPDATE games SET Platform ="MSX" WHERE Platform = "Microsoft MSX2+";
UPDATE games SET Platform ="pcengine" WHERE Platform = "NEC TurboGrafx-16";
UPDATE games SET Platform ="pcengine" WHERE Platform = "NEC TurboGrafx-CD";
UPDATE games SET Platform ="3ds" WHERE Platform = "Nintendo 3DS";
UPDATE games SET Platform ="n64" WHERE Platform = "Nintendo 64";
UPDATE games SET Platform ="n64dd" WHERE Platform = "Nintendo 64DD";
UPDATE games SET Platform ="nds" WHERE Platform = "Nintendo DS";
UPDATE games SET Platform ="nes" WHERE Platform = "Nintendo Entertainment System";
UPDATE games SET Platform ="gameandwatch" WHERE Platform = "Nintendo Game & Watch";
UPDATE games SET Platform ="gb" WHERE Platform = "Nintendo Game Boy";
UPDATE games SET Platform ="gba" WHERE Platform = "Nintendo Game Boy Advance";
UPDATE games SET Platform ="gbc" WHERE Platform = "Nintendo Game Boy Color";
UPDATE games SET Platform ="gc" WHERE Platform = "Nintendo GameCube";
UPDATE games SET Platform ="virtualboy" WHERE Platform = "Nintendo Virtual Boy";
UPDATE games SET Platform ="wii" WHERE Platform = "Nintendo Wii";
UPDATE games SET Platform ="pcengine" WHERE Platform = "PC Engine SuperGrafx";
UPDATE games SET Platform ="atomiswave" WHERE Platform = "Sammy Atomiswave";
UPDATE games SET Platform ="scummvm" WHERE Platform = "ScummVM";
UPDATE games SET Platform ="sega32x" WHERE Platform = "Sega 32X";
UPDATE games SET Platform ="segacd" WHERE Platform = "Sega CD";
UPDATE games SET Platform ="dreamcast" WHERE Platform = "Sega Dreamcast";
UPDATE games SET Platform ="gamegear" WHERE Platform = "Sega Game Gear";
UPDATE games SET Platform ="genesis" WHERE Platform = "Sega Genesis";
UPDATE games SET Platform ="mastersystem" WHERE Platform = "Sega Master System";
UPDATE games SET Platform ="naomi" WHERE Platform = "Sega Naomi";
UPDATE games SET Platform ="naomi" WHERE Platform = "Sega Naomi 2";
UPDATE games SET Platform ="saturn" WHERE Platform = "Sega Saturn";
UPDATE games SET Platform ="zxspectrum" WHERE Platform = "Sinclair ZX Spectrum";
UPDATE games SET Platform ="neogeo" WHERE Platform = "SNK Neo Geo AES";
UPDATE games SET Platform ="neogeocd" WHERE Platform = "SNK Neo Geo CD";
UPDATE games SET Platform ="neogeo" WHERE Platform = "SNK Neo Geo MVS";
UPDATE games SET Platform ="ngp" WHERE Platform = "SNK Neo Geo Pocket";
UPDATE games SET Platform ="ngpc" WHERE Platform = "SNK Neo Geo Pocket Color";
UPDATE games SET Platform ="psx" WHERE Platform = "Sony Playstation";
UPDATE games SET Platform ="ps2" WHERE Platform = "Sony Playstation 2";
UPDATE games SET Platform ="psp" WHERE Platform = "Sony PSP";
UPDATE games SET Platform ="snes" WHERE Platform = "Super Nintendo Entertainment System";
UPDATE games SET Platform ="wonderswan" WHERE Platform = "WonderSwan";
UPDATE games SET Platform ="wonderswan" WHERE Platform = "WonderSwan Color";
